OBJECTS = main.o \
          adc.o \
          pkts.o \
          gps.o

EXEC = unit

DEPS = libmspuartlink:gcc libartibeus:gcc libads:gcc libio:gcc libfixed:gcc \
				libmspware:gcc libmsp:gcc libgnss:gcc

include tools/maker/Makefile
